### ISSUE TITLE
possible race condition between Hugo and Search plugin

### ISSUE THREAD

**Issue by timhughes** [pedronasser/caddy-search#15]
Still seeing issue #9 when using the hugo plugin - looks like a race condition between the content being built and the indexed.  

```
$ caddy -version
Caddy 0.9.3
```

**Caddyfile**

```
0.0.0.0:2020                                                                     
gzip                                                                             
log  ./logs/access.log                                                           
basicauth /admin user pass                                                       
root ./goldfish/public                                                           
search ^/                                                                        
hugo ./goldfish {                                                                

}   
```

**Trace**

```
$ caddy
Activating privacy features... done.
http://0.0.0.0:2020
WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192".
/home/hughest/git/hugo_blog/goldfish/public/2009/05/libvirt-qpid-and-python/index.html
/home/hughest/git/hugo_blog/goldfish/public/2009/05/python-httpconnection-bound-to-network-interface/index.html
/home/hughest/git/hugo_blog/goldfish/public/2009/05/using-external-scripts-with-django-models/index.html
/home/hughest/git/hugo_blog/goldfish/public/2009/12/reinstall-centos-using-grub/index.html
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x4c0f53]

goroutine 43 [running]:
panic(0xbb1340, 0xc42000a1a0)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/pedronasser/caddy-search.ScanToPipe.func1(0xc4204f5040, 0x33, 0x0, 0x0, 0x1035440, 0xc4203cd260, 0x0, 0x0)
    /home/caddy/go/src/github.com/pedronasser/caddy-search/setup.go:85 +0x73
path/filepath.walk(0xc4203b0660, 0x30, 0x10425c0, 0xc4202c52b0, 0xc4202ca240, 0x0, 0x0)
    /usr/local/go/src/path/filepath/path.go:372 +0x22e
path/filepath.walk(0xc4202bef60, 0x2b, 0x10425c0, 0xc4202c44e0, 0xc4202ca240, 0x0, 0x1)
    /usr/local/go/src/path/filepath/path.go:376 +0x344
path/filepath.Walk(0xc4202bef60, 0x2b, 0xc4202ca240, 0x2b, 0x0)
    /usr/local/go/src/path/filepath/path.go:398 +0xd5
github.com/pedronasser/caddy-search.ScanToPipe(0xc4202e61c0, 0x11, 0xc4203237a0, 0x103e040, 0xc4203455e0, 0x0, 0x0)
    /home/caddy/go/src/github.com/pedronasser/caddy-search/setup.go:113 +0x128
github.com/pedronasser/caddy-search.Setup.func1(0xc4203141e0, 0xc4203237a0, 0x103e040, 0xc4203455e0, 0xc4202e9cc0)
    /home/caddy/go/src/github.com/pedronasser/caddy-search/setup.go:54 +0x60
created by github.com/pedronasser/caddy-search.Setup
    /home/caddy/go/src/github.com/pedronasser/caddy-search/setup.go:64 +0x18d
```

**Comment by pedronasser** [comment]
Agreed. It's probably a race condition for content between both plugins.
What can probably be done here is to correctly handle the `filepath.Walk` to skip when `err != nil`. 
That would prevent the panic.
But it would probably skip the search indexing.
We could also add a directive configuration like `wait 30s` so the index would start only after that time.
Another solution is to add a configuration to disable the initial scan. So the index would be created only dynamically.
@mholt

**Comment by timhughes** [comment]
I have no idea what it would entail so it may not make sense but maybe we could get the hugo plugin to have an optional 'call after' section that chains this plugin.

**Comment by timhughes** [comment]
Looks like a dead project, no commits in 3 years - closing
