### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by miekg** [pedronasser/caddy-search#9]
info can be `nil` in `ScanToPipe`, don't know how I managed to do that, but here you go:

```
localhost:2015
localhost:2016
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x38 pc=0x5e14d7]

goroutine 53 [running]:
panic(0xcc2300, 0xc82000a1c0)
    /home/miek/upstream/go/src/runtime/panic.go:464 +0x3e6
github.com/pedronasser/caddy-search.ScanToPipe.func1(0xc820183360, 0xc, 0x0, 0x0, 0x7fc53469d220, 0xc8202420c0, 0x0, 0x0)
    /home/miek/g/src/github.com/pedronasser/caddy-search/setup.go:82 +0x87
path/filepath.Walk(0xc820183360, 0xc, 0xc82023dee0, 0x0, 0x0)
    /home/miek/upstream/go/src/path/filepath/path.go:394 +0xa5
github.com/pedronasser/caddy-search.ScanToPipe(0xc820183360, 0xc, 0xc820234210, 0x7fc53469d568, 0xc820230aa0, 0x0, 0x0)
    /home/miek/g/src/github.com/pedronasser/caddy-search/setup.go:119 +0x99
github.com/pedronasser/caddy-search.Setup.func1(0xc8200b1500, 0xc820234210, 0x7fc53469d568, 0xc820230aa0, 0xc8202323c0)
    /home/miek/g/src/github.com/pedronasser/caddy-search/setup.go:47 +0x70
created by github.com/pedronasser/caddy-search.Setup
    /home/miek/g/src/github.com/pedronasser/caddy-search/setup.go:57 +0x265
[1+] % caddyext build
```

**Comment by miekg** [comment]
ah, nothing exists, the root source path of the site is empty.

**Comment by timhughes** [comment]
moved comment into a  new issue #15
